language: go
go:
  - 1.2.2
install:
  - go get -v code.google.com/p/go.tools/cmd/vet
  - go get -v github.com/tools/godep
  - go get -v github.com/onsi/ginkgo/ginkgo
script:  bin/test --compilers=2
branches:
  only:
  - master
  - /^hw-issue-.*$/
  - /^hwcf-issue-.*$/
before_install:
  - repo=`basename $PWD`; localDir=`dirname $PWD`; cfDir="`dirname $localDir`/cloudfoundry"
  - if [[ "$localDir" != "$cfDir" ]]; then mv "$localDir" "$cfDir"; cd ../../cloudfoundry/$repo; export TRAVIS_BUILD_DIR=`dirname $TRAVIS_BUILD_DIR`/$repo; fi
